import 'package:correspondencia_sipe_sipe/core/util/enums.dart';
import 'package:correspondencia_sipe_sipe/features/correspondence/domain/entities/correspondence_entity.dart';
import 'package:correspondencia_sipe_sipe/features/correspondence/domain/entities/correspondence_movement_entity.dart';

final externalCorrespondence = CorrespondenceEntity(
  id: 'corr-ext',
  uniqueNumber: 1,
  year: 2026,
  cite: 'CITE-2026-001',
  routeNumber: 'HR-2026-000001',
  type: CorrespondenceTypeCode.ce,
  priority: 'Alta',
  subject: 'Solicitud externa',
  senderName: 'Ciudadano Test',
  currentUnitId: 'unit-sistemas',
  currentUnitName: 'Unidad de Sistemas',
  currentUserId: 'user-dest',
  currentUserName: 'Usuario Destino',
  registeredAt: DateTime.utc(2026, 1, 15, 14, 30),
  statusLabel: 'Activo',
  documentTypeCode: 'EDIE',
  documentTypeName: 'Encadenamiento',
  documentNumber: '15/2026',
  reference: 'REF-001',
  originDescription: 'Ventanilla',
  senderDocument: '1234567',
  createdByUsername: 'admin',
);

final internalCorrespondence = CorrespondenceEntity(
  id: 'corr-int',
  uniqueNumber: 2,
  year: 2026,
  cite: '',
  routeNumber: 'HR-2026-000002',
  type: CorrespondenceTypeCode.ci,
  priority: 'Media',
  subject: 'Memorándum interno',
  currentUnitId: 'unit-secretaria',
  currentUnitName: 'Secretaría',
  registeredAt: DateTime.utc(2026, 1, 16, 9, 15),
  statusLabel: 'Activo',
  documentTypeCode: 'INFORME',
  documentTypeName: 'Informe Técnico',
  originEmployeeName: 'Juan Pérez',
  originUnitName: 'Sistemas',
);

final notaCorrespondence = CorrespondenceEntity(
  id: 'corr-nota',
  uniqueNumber: 3,
  year: 2026,
  cite: '',
  routeNumber: 'HR-2026-000003',
  type: CorrespondenceTypeCode.ci,
  priority: 'Baja',
  subject: 'Nota interna',
  currentUnitName: 'Sistemas',
  registeredAt: DateTime.utc(2026, 1, 17, 11, 0),
  statusLabel: 'Activo',
  documentTypeCode: 'NOTA',
  documentTypeName: 'Nota Interna',
  originEmployeeName: 'María López',
);

final inactiveResponsibleCorrespondence = CorrespondenceEntity(
  id: 'corr-inactive-user',
  uniqueNumber: 4,
  year: 2026,
  cite: '',
  routeNumber: 'HR-2026-000004',
  type: CorrespondenceTypeCode.ci,
  priority: 'Media',
  subject: 'Trámite con responsable inactivo',
  currentUnitId: 'unit-juridica',
  currentUnitName: 'Dirección Jurídica',
  currentUserId: 'user-carlos',
  currentUserName: 'Carlos Pérez',
  currentUserIsActive: false,
  registeredAt: DateTime.utc(2026, 1, 18, 8, 0),
  statusLabel: 'Activo',
  documentTypeCode: 'NOTA',
  documentTypeName: 'Nota Interna',
);

final vigenteMovement = CorrespondenceMovementEntity(
  id: 'mov-1',
  sequenceNumber: 1,
  movementType: 'CREATED',
  movementTypeLabel: 'Registro',
  toUnitName: 'Sistemas',
  toUserName: 'Usuario Destino',
  instruction: 'Atender',
  createdByUsername: 'admin',
  createdAt: DateTime.utc(2026, 1, 15, 10),
);

final cancelledMovement = CorrespondenceMovementEntity(
  id: 'mov-2',
  sequenceNumber: 2,
  movementType: 'DERIVED',
  movementTypeLabel: 'Derivación',
  fromUnitName: 'Sistemas',
  toUnitName: 'Secretaría',
  instruction: 'Revisar',
  createdByUsername: 'admin',
  createdAt: DateTime.utc(2026, 1, 16, 11),
  cancelledAt: DateTime.utc(2026, 1, 17),
  cancellationReason: 'Error de destino',
);
