"""case insensitive unique constraints

Revision ID: dedae3fe9eb8
Revises: bcdb2dd8bd5b
Create Date: 2026-09-21 19:29:57.530558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedae3fe9eb8'
down_revision: Union[str, None] = 'bcdb2dd8bd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index('uq_users_email_lower', 'users', [sa.text('LOWER(email)')], unique=True)
    op.create_index('uq_users_username_lower', 'users', [sa.text('LOWER(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
