"""Stable codes for correspondence domain (milestone 1)."""

CORRESPONDENCE_TYPE_INTERNAL = "INTERNAL"
CORRESPONDENCE_TYPE_EXTERNAL = "EXTERNAL"

STATUS_ACTIVE = "ACTIVE"
STATUS_CONCLUDED = "CONCLUDED"

PRIORITY_HIGH = "HIGH"
PRIORITY_MEDIUM = "MEDIUM"
PRIORITY_LOW = "LOW"
PRIORITY_CODES = frozenset({PRIORITY_HIGH, PRIORITY_MEDIUM, PRIORITY_LOW})

MOVEMENT_CREATED = "CREATED"
MOVEMENT_DERIVED = "DERIVED"
MOVEMENT_RECEIVED = "RECEIVED"
MOVEMENT_RESPONDED = "RESPONDED"
MOVEMENT_CONCLUDED = "CONCLUDED"
MOVEMENT_REOPENED = "REOPENED"
MOVEMENT_CANCELLED = "CANCELLED"
MOVEMENT_ANNULLED = "ANNULLED"

# Provisional technical format until GAM Sipe Sipe confirms official rules.
ROUTE_NUMBER_PREFIX = "HR"

GENERATED_ENCADENAMIENTO_PREFIX = "encadenamiento_"
GENERATED_ENCADENAMIENTO_MIME = "application/pdf"

# Valores conceptuales para futuro attachment_kind / source (sin columna DB aún).
ATTACHMENT_SOURCE_UPLOADED = "UPLOADED"
ATTACHMENT_SOURCE_GENERATED_CHAINING = "GENERATED_CHAINING"
